<?php
// Gathering the Database connection variables file
require_once("config/db.php");

// Gathering the Login Class
require_once("classes/Login.php");

// Creating a new login token
$login = new Login();

// If-Else statement checking if the user is logged in
if ($login->isUserLoggedIn() == true) {
    // If they are, then it will show the header for logged in users
    include_once 'headerloggedin.php';
} else {
    // Otherwise it will show the default header
    include_once 'header.php';
}
?>

<br><br>

<!-- 
    This accessibility statement was autogenerated to give an idea of what it would look like. 
    The contents is courtesy of: W3C Accessibility Statement Generator Tool which can be found at
    https://www.w3.org/WAI/planning/statements/
-->
<div class="d-flex justify-content-center">
    <div class="p-2"></div>
    <div class="p-2 justify-content-center" style="text-align: justify; width: 75%;">

        <h2>Accessibility Statement for <span class="basic-information website-name">AONB Locator</span></h2>
        <p>
            <span class="basic-information organization-name">AONB Locator</span>
            is committed to ensuring digital accessibility for people with disabilities.
            We are continually improving the user experience for everyone, and applying the relevant accessibility standards.
        </p>
        <h3>Measures to support accessibility</h3>
        <p>
            <span class="basic-information organization-name">AONB Locator</span>
            takes the following measures to ensure accessibility of
            <span class="basic-information website-name">AONB Locator</span>:
        </p>
        <ul class="organizational-effort accessibility-measures">
            <li>Include accessibility as part of our mission statement.</li>
            <li>Include accessibility throughout our internal policies.</li>
            <li>Integrate accessibility into our procurement practices.</li>
            <li>Appoint an accessibility officer and/or ombudsperson.</li>
            <li>Provide continual accessibility training for our staff.</li>
            <li>Assign clear accessibility targets and responsibilities.</li>
            <li>Employ formal accessibility quality assurance methods.</li>
        </ul>
        <h3>Conformance status</h3>
        <p>
            The <a href="https://www.w3.org/WAI/standards-guidelines/wcag/">Web Content Accessibility Guidelines (WCAG)</a> defines requirements for designers and developers to improve accessibility for people with disabilities. It defines three levels of conformance: Level A, Level AA, and Level AAA.
            <span class="basic-information website-name">AONB Locator</span>
            is
            <span class="basic-information conformance-status" data-printfilter="lowercase">not assessed</span>
            with
            <span class="basic-information conformance-standard"><span data-negate="">WCAG 2.1 level AA</span>.</span>
            <span>
                <span class="basic-information conformance-status">Not assessed</span>
                means that
                <span class="basic-information conformance-meaning">the content has not been evaluated or the evaluation results are not available</span>.
            </span>
        </p>
        <hr noshade="noshade">
        <p>
            This statement was created on
            <span class="basic-information statement-created-date">4 March 2021</span>
            using the <a href="https://www.w3.org/WAI/planning/statements/">W3C Accessibility Statement Generator Tool</a>.
        </p>
    </div>
</div>

<?php
    include_once 'footer.php';
?>
